"""Theorem M figure: the optimal set is a level set, and it climbs a ladder.

A1 treated the sensitivity optimum as a wavelength.  Theorem M
(`theory_a2_multiplicity.py`) says it is a *set*: under assumption (M) every
wavelength solving a(lambda) = Gamma_p*/(gamma I A_max) is an exactly
equivalent optimum, so the optimal set is a level set of the reconstructed
kernel and its cardinality N steps whenever the level crosses a critical value
of a.  This figure shows both halves of that statement on the frozen 120 GPa
Ho kernel.

Panel (a) is the geometry.  The fixed-power figure of merit
a(lambda) = A(lambda)/A_max carries four interior local maxima inside the
402-517 nm data window, not one, and a horizontal level line therefore meets
the curve in several places at once.  Panel (b) is the consequence: N as a step
function of power, with each step falling on the critical value that Theorem M
says produces it.

What this figure must NOT be used to claim
------------------------------------------
* **It is not a measurement.**  Every value comes from the kernel
  reconstructed from Ho et al. Fig. 1(e); see ``esa_figv_kernel_sanity.py``
  for what that reconstruction is and is not good for.  In particular the
  zero-phonon line at 514.46 nm is extracted from a feature the source figure
  clips, so its height carries the uncertainty flagged in erratum E3 and is
  quantitatively trustworthy only below ~40 GPa.
* **The N = 6 plateau is not a prediction anyone can test.**  It spans a
  factor 1.003 in power.  It is drawn because Theorem M puts it there, and
  labelled as unresolvable so that it is never quoted as an observable.
* **The absolute power scale is not fixed.**  The abscissa of panel (b) is
  I/I_c, a ratio of measured rate-spectrum values; nothing here calibrates
  gamma, A_max, or Gamma_p*.
* Panel (a) shows *degeneracy*, not a ranking.  The marked intersections are
  equally good, which is the point; the curve height at the marks is not a
  sensitivity.

The rung positions, the wavelength that generates each and the N it steps
between are tabulated in the manuscript, not lettered into panel (b): the
panel draws the six rungs numbered k = 1..6 and the table carries the
numbers.  Rungs 2 and 3 differ by 0.3 % in power and share one numeral.

One of the six is not a statement about the defect.  The rung at I/I_c = 1.86
is generated by the blue edge of the analysis window, which is where the
source figure stops rather than where the absorption band ends, so it is drawn
in grey and named a window-censoring rung.  Theorem M's Delta-N = -1 edge case
is real -- any finite scan window produces one -- but *this* edge sits at
402 nm because of how the source figure was cropped.

Run for the figure and the numbers quoted in the caption:

    python fig_m_level_set_ladder.py
"""
from pathlib import Path

import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.lines import Line2D

import fig_style
from theory_a1_generalization import DATA_WINDOW, Kernel
from theory_a2_multiplicity import (critical_values, match_transitions,
                                    observed_ladder, plateau_widths)

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
OUT_PNG = HERE / 'outputs' / 'figures' / 'fig_m_level_set_ladder.png'
OUT_PDF = ROOT / 'paper' / 'figures' / 'fig_m_level_set_ladder.pdf'

# Okabe-Ito, colourblind safe.  Every colour is paired with a linestyle or a
# marker so the figure survives greyscale reproduction.
BLACK = '#000000'
ORANGE = '#E69F00'
SKY = '#56B4E9'
GREEN = '#009E73'
BLUE = '#0072B2'
VERMILLION = '#D55E00'
PURPLE = '#CC79A7'

# Rungs generated by an interior critical point of a are predictions about
# the defect.  The rung at the blue edge is not: it is generated by the
# wavelength at which the source figure was cropped, so it is drawn apart from
# the others rather than alongside them.
RUNG_COLOUR = VERMILLION
RUNG_DASHES = (0, (5, 2))
EDGE_COLOUR = '0.45'
EDGE_DASHES = (0, (1, 1.6))
EDGE_KINDS = ('edge-blue', 'edge-red')

# Rungs whose power ratios differ by less than this fraction cannot carry
# separate numerals at this scale and share one label.
RUNG_LABEL_MERGE = 0.02

# Height, in data units, at which the rung numerals sit in panel (b), and
# the height the rung verticals stop at.  They are cut short so the legend
# above them sits on clear paper instead of being crossed by six lines.
RUNG_LABEL_Y = 7.1
RUNG_TOP = 8.0


def level_line(kernel, margin=5e-4):
    """A level just above the 475.55 nm maximum: four members, none merged.

    Sitting exactly on a critical value makes the membership count ambiguous,
    so the drawn level is lifted by `margin`, which puts it inside the N = 4
    plateau that Theorem M places between the ZPL rung and the 475.55 nm rung.
    """
    second = kernel.local_maxima()[1][1]
    level = second * (1.0 + margin)
    return level, kernel.level_set(level, DATA_WINDOW, step=0.002)


def _kernel_panel(ax, kernel, level, members):
    grid = np.arange(kernel.lam_min, kernel.lam_max + 1e-9, 0.002)
    ax.plot(grid, kernel.a(grid), color=BLACK, lw=1.1, zorder=3)

    ax.axhline(level, color=VERMILLION, lw=1.2, ls=(0, (6, 2)), zorder=2,
               label=r'level $a^{*}$ at $I/I_c = %.2f$' % (1.0 / level))
    ax.plot(members, [level] * len(members), 'o', color=VERMILLION,
            ms=5.0, mfc='white', mew=1.4, zorder=5,
            label='optimal set: %d members' % len(members))

    maxima = kernel.local_maxima()
    ax.plot([m[0] for m in maxima], [m[1] for m in maxima], 'v', color=BLUE,
            ms=4.6, zorder=6, label='interior local maxima of $a$')

    ax.set_xlim(kernel.lam_min, kernel.lam_max)
    ax.set_ylim(0.0, 1.14)
    ax.set_xlabel('Wavelength (nm)')
    ax.set_ylabel(r'$a(\lambda)=A(\lambda)/A_{\max}$')
    ax.set_title('(a)', loc='left')
    ax.grid(alpha=0.22, lw=0.5)
    ax.legend(frameon=False, loc='lower left', handlelength=2.4,
              borderaxespad=0.4, labelspacing=0.35)


def rung_labels(rows, merge=RUNG_LABEL_MERGE):
    """Numeral, and where to put it, for each rung of the ladder.

    Rungs 2 and 3 sit 0.3 % apart in power.  Two numerals cannot be told
    apart there at page size, so consecutive rungs closer than `merge` are
    collapsed into one label reading ``2,3`` at their midpoint.
    """
    groups = []
    for index, row in enumerate(rows, start=1):
        ratio = row['predicted_power_ratio']
        if groups and ratio / groups[-1][-1][1] - 1.0 < merge:
            groups[-1].append((index, ratio))
        else:
            groups.append([(index, ratio)])
    return [(','.join(str(index) for index, _ in group),
             float(np.mean([np.log10(ratio) for _, ratio in group])))
            for group in groups]


def _ladder_panel(ax, ladder, rows):
    ratios, counts = ladder['ratios'], ladder['counts']
    step, = ax.step(np.log10(ratios), counts, where='post', color=BLACK,
                    lw=1.4, zorder=4, label='$N(I)$ from the kernel')

    # One style for all six: they are the same object, and the numeral above
    # each keys it to the ladder table in the manuscript.  Putting the power
    # ratio, the generating wavelength and the step into the legend, as this
    # panel used to, reproduced that table on top of the data.
    for row in rows:
        edge = row['kind'] in EDGE_KINDS
        ax.vlines(np.log10(row['predicted_power_ratio']), 1.4, RUNG_TOP,
                  color=EDGE_COLOUR if edge else RUNG_COLOUR,
                  ls=EDGE_DASHES if edge else RUNG_DASHES,
                  lw=1.0, zorder=2)

    # Rung 1 and the merged pair 2,3 are only 3 % of the abscissa apart, which
    # is narrower than the numerals themselves.  A label whose neighbour is
    # that close is set to the left of its own rule and the neighbour to the
    # right, and the second of the pair drops to a lower row.
    span = float(np.log10(ratios[-1]))
    labels = rung_labels(rows)
    for index, (label, position) in enumerate(labels):
        nxt = labels[index + 1][1] if index + 1 < len(labels) else None
        prv = labels[index - 1][1] if index else None
        leads = nxt is not None and nxt - position < 0.07 * span
        trails = prv is not None and position - prv < 0.07 * span
        ax.annotate(label, xy=(position, RUNG_LABEL_Y - (1.0 if trails else 0.0)),
                    xytext=(-2.5 if leads else 2.5, 2),
                    textcoords='offset points',
                    ha='right' if leads else 'left', va='bottom',
                    fontsize=fig_style.ANNOT, color=RUNG_COLOUR)

    rung_proxy = Line2D([], [], color=RUNG_COLOUR, ls=RUNG_DASHES, lw=1.0,
                        label='rungs $k$ from critical points of $a$')
    edge_proxy = Line2D([], [], color=EDGE_COLOUR, ls=EDGE_DASHES, lw=1.0,
                        label='window-censoring rung')

    ax.set_xlim(0.0, float(np.log10(ratios[-1])))
    ax.set_ylim(1.4, 11.2)
    ax.set_yticks([2, 3, 4, 5, 6])
    ax.set_xlabel(r'$\log_{10}(I/I_c)$')
    ax.set_ylabel('Multiplicity $N$ of the optimal set')
    ax.set_title('(b)', loc='left')
    ax.grid(alpha=0.22, lw=0.5)
    ax.legend(handles=[step, rung_proxy, edge_proxy], frameon=False,
              loc='upper right', handlelength=2.4, borderaxespad=0.5,
              labelspacing=0.35)


def main():
    kernel = Kernel()
    level, members = level_line(kernel)
    matched = match_transitions(kernel)
    rows = matched['rows']
    plateaux = plateau_widths(kernel)

    fig_style.use()
    fig, axes = plt.subplots(1, 2, figsize=(fig_style.FULL_WIDTH_IN, 3.35))
    fig.subplots_adjust(left=0.082, right=0.985, bottom=0.155, top=0.930,
                        wspace=0.27)

    _kernel_panel(axes[0], kernel, level, members)
    _ladder_panel(axes[1], observed_ladder(kernel), rows)

    print(fig_style.save(fig, OUT_PNG, OUT_PDF) + '\n')
    print('panel (a): interior local maxima of a(lambda) over %.0f-%.0f nm'
          % DATA_WINDOW)
    for lam, value in kernel.local_maxima():
        print('    %8.2f nm   a = %.4f' % (lam, value))
    print('  level line a* = %.6f  (I/I_c = %.4f), %d members:'
          % (level, 1.0 / level, len(members)))
    print('    ' + '  '.join('%.3f' % m for m in members))

    print('\npanel (b): critical values and the rungs they predict')
    print('    a        lambda [nm]  kind        I/I_c     dN')
    for critical in critical_values(kernel):
        print('    %.4f   %9.2f  %-10s  %7.4f  %+d'
              % (critical.level, critical.wavelength, critical.kind,
                 critical.power_ratio, critical.delta_multiplicity))
    print('  observed ladder (bisected to 1e-4 in I/I_c)')
    print('    I/I_c obs   I/I_c pred   from [nm]   kind        N       err')
    for row in rows:
        print('    %9.4f   %10.4f   %9.2f   %-10s  %d->%d   %.2e'
              % (row['observed_power_ratio'], row['predicted_power_ratio'],
                 row['predicted_from_nm'], row['kind'],
                 row['before'], row['after'], row['relative_error']))
    print('  plateau widths')
    for row in plateaux:
        end = ('inf' if not np.isfinite(row['to_power_ratio'])
               else '%.4f' % row['to_power_ratio'])
        width = ('inf' if not np.isfinite(row['width_factor'])
                 else 'x%.4f' % row['width_factor'])
        print('    N = %d: I/I_c in [%.4f, %s]  width %s'
              % (row['multiplicity'], row['from_power_ratio'], end, width))


if __name__ == '__main__':
    main()
